# Generated by Django 4.0.4 on 2022-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutisticData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('refferedBy', models.CharField(max_length=50)),
            ],
        ),
    ]
