# Generated by Django 4.0.4 on 2022-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autisticdata',
            name='behavioral_concerns',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='birthDate',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='birthWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='caseno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='consanguinity',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='delivery',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='developemental_concerns',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='learning_concerns',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='neurological_concern',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='perninantalEvents',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='requiredNICUstay',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='term',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='treatment',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
