# Generated by Django 4.0.4 on 2022-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_autisticdata_behavioral_concerns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autisticdata',
            name='communication_loops',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='full_sentences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='motor_development',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='neck_holding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='reapeats_spoken_words',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='response_to_calling_names',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='response_to_instructions',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='roll_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='single_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='sitting_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='social_smile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='speech_developement',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='standing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='walking',
            field=models.IntegerField(default=0),
        ),
    ]
