# Generated by Django 4.0.4 on 2022-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_autisticdata_communication_loops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autisticdata',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='autisticdata',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='autisticdata',
            name='gender',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='autisticdata',
            name='refferedBy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
