# Generated by Django 4.0.4 on 2022-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_autisticdata_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autisticdata',
            name='clinical_history_significance',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='ho_hospitalization',
            field=models.CharField(default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='ho_previous_treatment',
            field=models.CharField(default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='ho_surgery',
            field=models.CharField(default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='past_history_significance',
            field=models.CharField(default='not significant', max_length=20),
        ),
    ]
