# Generated by Django 4.0.4 on 2022-06-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_autisticdata_parenting_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='autisticdata',
            name='attendance',
            field=models.TextField(default='average'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='concerns_first_noticed_in',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='liked_subjects',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='present_school_concerns',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='present_school_name',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='school_board',
            field=models.TextField(default='state'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='school_comments',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='school_medium',
            field=models.TextField(default='english'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='unliked_subjects',
            field=models.TextField(default='NA'),
        ),
    ]
