# Generated by Django 4.0.4 on 2022-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_autisticdata_deliverydetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autisticdata',
            name='sno',
        ),
        migrations.AlterField(
            model_name='autisticdata',
            name='caseno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
