# Generated by Django 4.0.4 on 2022-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_autisticdata_sno_alter_autisticdata_caseno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autisticdata',
            name='past_history_significance',
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='BehavioralAndPersonalDetails',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='PastHistoryDetails',
            field=models.TextField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='UnhealthyDietryHabits',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='UnhealthySleepHabits',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='climbing_staircase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='delayed_motor_developement',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='delayed_sensory_dev',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='motorDevDetails',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='preterm_weeks',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='referredBy_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='autisticdata',
            name='tv_view_hrs',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='autisticdata',
            name='birthWeight',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
