# Generated by Django 4.0.4 on 2022-07-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_autisticdata_past_history_significance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autisticdata',
            name='delayed_speech_developement',
            field=models.TextField(default='NA'),
        ),
    ]
