# Generated by Django 4.0.4 on 2022-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_autisticdata_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.EmailField(max_length=254)),
                ('contactNo', models.TextField(default='')),
                ('username', models.TextField(default='', max_length=50)),
                ('password', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
