# Generated by Django 4.0.4 on 2022-07-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCred',
        ),
    ]
