# Generated by Django 4.0.4 on 2022-07-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_usercred_autisticdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autisticdata',
            old_name='BehavioralAndPersonalDetails',
            new_name='Behavioral_And_Personal_Details',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='PastHistoryDetails',
            new_name='Past_History_Details',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='UnhealthyDietryHabits',
            new_name='Unhealthy_Dietry_Habits',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='UnhealthySleepHabits',
            new_name='Unhealthy_Sleep_Habits',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='birthDate',
            new_name='birth_Date',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='birthWeight',
            new_name='birth_Weight',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='deliveryDetails',
            new_name='delivery_Details',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='motorDevDetails',
            new_name='motor_devlopement_details',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='perninantalEvents',
            new_name='perninantal_Events',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='perninantalEventsDetails',
            new_name='perninantal_Events_Details',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='referredBy_phone',
            new_name='referred_By_phone_no',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='refferedBy',
            new_name='reffered_By',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='requiredNICUstay',
            new_name='required_NICU_stay',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='speechDevDetails',
            new_name='speech_devlopement_details',
        ),
    ]
