# Generated by Django 4.0.4 on 2022-07-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_behavioralandpersonaldetails_autisticdata_behavioral_and_personal_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autisticdata',
            old_name='caseno',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='autisticdata',
            old_name='followUpPlan',
            new_name='follow_Up_Plan',
        ),
    ]
