# Generated by Django 4.0.4 on 2022-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_caseno_autisticdata_case_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autisticdata',
            name='case_no',
            field=models.AutoField(default=0, primary_key=True, serialize=True),
        ),
    ]
