# Generated by Django 4.0.4 on 2022-08-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_autisticdata_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autisticdata',
            name='case_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
