# Generated by Django 4.0.4 on 2022-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.EmailField(max_length=254)),
                ('contactNo', models.TextField(default='')),
                ('username', models.TextField(default='', max_length=50)),
                ('password', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
