from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class AutisticData(models.Model):
    user=models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    case_no=models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=50,default='',null=True)
    address = models.TextField(default='',null=True)
    gender=models.CharField(max_length=20,default='',null=True)
    reffered_By= models.CharField(max_length=50,default='',null=True)
    referred_By_phone_no = models.CharField(max_length=50,default='',null=True)
    
    # Birth history
    birth_Date=models.CharField(max_length=20,default='',null=True)
    birth_Weight=models.CharField(max_length=20,default='',null=True)
    term=models.CharField(max_length=20,default='40')
    preterm_weeks=models.CharField(max_length=20,default='',null=True)
    delivery=models.CharField(max_length=20,default='',null=True)
    delivery_Details=models.CharField(max_length=1000,default='',null=True)
    consanguinity=models.CharField(max_length=20,default='',null=True)
    perninantal_Events=models.CharField(max_length=20,default='',null=True)
    perninantal_Events_Details=models.CharField(max_length=1000,default='',null=True)
    treatment=models.CharField(max_length=20,default='',null=True)
    required_NICU_stay=models.CharField(max_length=20,default='',null=True)
    
    #Concerns
    neurological_concern=models.TextField(default='',null=True)
    developemental_concerns=models.TextField(default='',null=True)
    delayed_motor_developement=models.TextField(default='',null=True)
    delayed_sensory_dev=models.TextField(default='',null=True)
    delayed_speech_developement=models.TextField(default='',null=True)
    learning_concerns=models.TextField(default='',null=True)
    behavioral_concerns=models.TextField(default='',null=True)
    
    #Developement History
    motor_development=models.CharField(max_length=20,default='',null=True)
    social_smile=models.IntegerField(default=0,null=True)
    neck_holding=models.IntegerField(default=0,null=True)
    roll_over=models.IntegerField(default=0,null=True)
    sitting_up=models.IntegerField(default=0,null=True)
    standing=models.IntegerField(default=0,null=True)
    climbing_staircase=models.IntegerField(default=0,null=True)
    walking=models.IntegerField(default=0,null=True)
    speech_developement=models.CharField(max_length=20,default='',null=True)
    single_words=models.IntegerField(default=0,null=True)
    full_sentences=models.IntegerField(default=0,null=True)
    response_to_calling_names=models.CharField(max_length=20,default='',null=True)
    response_to_instructions=models.CharField(max_length=20,default='',null=True)
    reapeats_spoken_words=models.CharField(max_length=20,default='',null=True)
    communication_loops=models.CharField(max_length=20,default='',null=True)
    motor_devlopement_details=models.TextField(default='',null=True)
    speech_devlopement_details=models.TextField(default='',null=True)
    
    #Past history
    clinical_history_significance=models.CharField(max_length=20,default='',null=True)
    ho_surgery=models.CharField(max_length=20,default='',null=True)
    ho_hospitalization=models.CharField(max_length=20,default='',null=True)
    ho_previous_treatment=models.CharField(max_length=20,default='',null=True)
    Past_History_Details=models.TextField(max_length=20,default='',null=True)
    
    #
    personal_developement=models.TextField(default='',null=True)
    learning_behavior=models.TextField(default='',null=True)
    behavior=models.TextField(default='',null=True)
    parenting_style=models.CharField(max_length=20,default='',null=True)
    Behavioral_And_Personal_Details=models.TextField(default='',null=True)
    
    #academic history
    pre_primary_school_Name=models.TextField(default='',null=True)
    pre_primary_school_Board=models.TextField(default='',null=True)
    pre_primary_school_Medium=models.TextField(default='',null=True)
    pre_primary_school_Comments=models.TextField(default='',null=True)
        
    primary_school_Name=models.TextField(default='',null=True)
    primary_school_Board=models.TextField(default='',null=True)
    primary_school_Medium=models.TextField(default='',null=True)
    primary_school_Comments=models.TextField(default='',null=True)
        
    secondary_school_Name=models.TextField(default='',null=True)
    secondary_school_Board=models.TextField(default='',null=True)
    secondary_school_Medium=models.TextField(default='',null=True)
    secondary_school_Comments=models.TextField(default='',null=True)
        
    prensent_school_Name=models.TextField(default='',null=True)
    prensent_school_Board=models.TextField(default='',null=True)
    prensent_school_Medium=models.TextField(default='',null=True)
    prensent_school_Comments=models.TextField(default='',null=True)
    
    attendance=models.TextField(default='',null=True)
    liked_subjects=models.TextField(default='',null=True)
    unliked_subjects=models.TextField(default='',null=True)
    present_school_concerns=models.TextField(default='',null=True)
    tv_view_hrs=models.CharField(max_length=20,default='',null=True)
    Unhealthy_Dietry_Habits=models.TextField(default='',null=True)
    Unhealthy_Sleep_Habits=models.TextField(default='',null=True)
    
    weight=models.TextField(default='',null=True)
    height=models.TextField(default='',null=True)
    head_circumference=models.IntegerField(default=0,null=True)
    skull_shape=models.TextField(default='',null=True)
    examination_neurology_details=models.TextField(default='',null=True)
    skin_exam=models.TextField(default='',null=True)
    joints=models.TextField(default='',null=True)
    examination_neurology=models.TextField(default='',null=True)
    neurology_details=models.TextField(default='',null=True)
    hypertrophy_of_muscles=models.TextField(default='',null=True)
    abnormal_tone_pattern=models.TextField(default='',null=True)
    muscle_tone_neurology=models.TextField(default='',null=True)
    muscle_neurology=models.TextField(default='',null=True)
    muscle_neurology_details=models.TextField(default='',null=True)
    muscle_power_details=models.TextField(default='',null=True)
    deep_tendon_reflexes=models.TextField(default='',null=True)
    deep_tendon_reflexes_details=models.TextField(default='',null=True)
    coordination=models.TextField(default='',null=True)
    ankle_dorsiflexion_left=models.TextField(default='',null=True)
    ankle_dorsiflexion_right=models.TextField(default='',null=True)
    adductor_angle_left=models.TextField(default='',null=True)
    adductor_angle_right=models.TextField(default='',null=True)
    popliteal_angle=models.TextField(default='',null=True)
    LUL=models.TextField(default='',null=True)
    LLL=models.TextField(default='',null=True)
    RUL=models.TextField(default='',null=True)
    RLL=models.TextField(default='',null=True)
    fnf_test=models.TextField(default='',null=True)
    dysdidocokinesia=models.TextField(default='',null=True)
    
    coordination_details=models.TextField(default='',null=True)
    abnormal_movements=models.TextField(default='',null=True)
    abnormal_movements_details=models.TextField(default='',null=True)
    motor_deficit=models.TextField(default='',null=True)
    gait=models.TextField(default='',null=True)
    balance=models.TextField(default='',null=True)
    
    #evaluation
    visual_deficit=models.TextField(default='',null=True)
    visual_deficits_details=models.TextField(default='',null=True)
    hearing_deficit=models.TextField(default='',null=True)
    hearing_deficits_details=models.TextField(default='',null=True)
    eye_contact=models.TextField(default='',null=True)
    motor_imitation_skills=models.TextField(default='',null=True)
    pointing_behaviors=models.TextField(default='',null=True)
    stereotypic_behaviors=models.TextField(default='',null=True)
    motor_details=models.TextField(default='',null=True)
    sensory_defensive_behaviors=models.TextField(default='',null=True)
    speech=models.TextField(default='',null=True)
    evaluationMChat=models.TextField(default='',null=True)
    development_screening=models.TextField(default='',null=True)
    gross_motor=models.TextField(default='',null=True)
    speech_screening=models.TextField(default='',null=True)
    fine_motor=models.TextField(default='',null=True)
    social_emotion=models.TextField(default='',null=True)
    learning_evaluation=models.TextField(default='',null=True)
    behavior_evaluation=models.TextField(default='',null=True)
    
    #impression
    neurology_impression=models.TextField(default='',null=True)
    cerebral_palsy=models.TextField(default='',null=True)
    cognitive_disability=models.TextField(default='',null=True)
    
    developement_impression=models.TextField(default='',null=True)
    learning_impression=models.TextField(default='',null=True)
    behavior_impression=models.TextField(default='',null=True)
    learning_difference=models.TextField(default='',null=True)
    Impression_Details=models.TextField(default='',null=True)
    
    #plan
    investigations=models.TextField(default='',null=True)
    investigations_details=models.TextField(default='',null=True)
    plan_reference=models.TextField(default='',null=True)
    iq_evaluation=models.TextField(default='',null=True)
    speech_lang_evaluation=models.TextField(default='',null=True)
    dq_evaluation=models.TextField(default='',null=True)
    sq_evaluation=models.TextField(default='',null=True)
    academic_achievements=models.TextField(default='',null=True)
    learning_evaluation_plan=models.TextField(default='',null=True)
    special_education_intervention=models.TextField(default='',null=True)
    remedial_intervention=models.TextField(default='',null=True)
    behavioral_modification=models.TextField(default='',null=True)
    academic_suggestions=models.TextField(default='',null=True)
    academic_suggestions_details=models.TextField(default='',null=True)
    follow_Up_Plan=models.TextField(default='',null=True)
    
    
    developemental_intervention=models.TextField(default='',null=True)
    remedial_intervention_details=models.TextField(default='',null=True)
    behavior_intervention=models.TextField(default='',null=True)
    eclectic_program=models.TextField(default='',null=True)
    developemental_therapy=models.TextField(default='',null=True)
    
    #medical treatment
    medical_treatment_plan=models.TextField(default='',null=True)
    